server:
    error:
        include-message: always
        include-binding-errors: always

spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/registration
        username: postgres
        password: Y%RdGm!-Tg/2zw(
    jpa:
        hibernate:            
            ddl-auto: create-drop
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format: true
        show-sql: true