server:
    error:
        include-message: always
        include-binding-errors: always

spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/registration
        username: postgres
        password: Y%RdGm!-Tg/2zw(
    jpa:
        hibernate:            
            ddl-auto: create-drop
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format: true
        show-sql: true
    mail:
        host: smtp.gmail.com
        port: 587
        username: your@gmail.com
        password: trarara
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true